#!/bin/bash
#
# Drive map display utility, by Massimo Santoro <massimosantoro@gmail.com>

VERSION=0.1 

# Copyright (C) 2018 Massimo Santoro.  All rights reserved.
#
# Requires dd and xxd.
# This needs to be redone entirely in C, someday.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License Version 3,
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# Usage: drivemap device [detail] [start] [end]

if [ -z $1 ]; then
	echo "Usage: drivemap device [detail] [start] [end]"
	echo "Please specify device name directly. Eg: drivemap sda [options]"
	exit 1
fi

if [ $USER != "root" ]; then
	echo "WARNING: drivemap requires root (at the moment)"
	exit 1
fi

if [ ! -z $2 ]; then
	if [ ! -z $3 ]; then
		if [ ! -z $4 ]; then
			linescount=$4
		else
			linescount=$2
		fi
		startpos=$3
	else
		startpos=0
		linescount=$2
	fi
else
	linescount=64
fi

device=$1
lastpos=$(( linescount - 1 ))

drivesizeb=$(cat /proc/partitions | grep $device'$' | rev | cut -d' ' -f2 | rev)
drivesizeg=$(( drivesizeb / 1048576 ))

echo "Drive Map - Device: "$device" Size: "$drivesizeb" bytes / "$drivesizeg" GB"

for i in `seq $startpos $lastpos`; do
	pos=$(( i * drivesizeb / linescount ))
	dd if=/dev/$device of=/var/tmp/drivemap.tmp bs=1024 count=1 skip=$pos &> /dev/null
	printf "Position: "$i"\t - bytes: "$pos"\t - GB:"$(( pos / 1048576 ))"\t - sample: " 
	xxd -ps -c 128 /var/tmp/drivemap.tmp | head -n 1 | cut -c-32
done
